from flask import Blueprint, jsonify
from flask_login import login_required
from collections import defaultdict
from datetime import datetime

import models.service as service_model
import models.work as work_model
import models.payment as payment_model
from utils import db as _db

api_bp = Blueprint('api', __name__, url_prefix='/api')

@api_bp.route('/services/<service_id>/price')
@login_required
def get_service_price(service_id):
    """
    Returns the standard price of a service in JSON.
    Used for live AJAX autofill when logging a project.
    """
    if _db.is_enabled():
        service = _db.get_service_by_id(service_id)
        if service:
            return jsonify({'price': float(service.get('price', 0.0))})
    else:
        service = service_model.get_service_by_id(service_id)
        if service:
            return jsonify({'price': float(service.get('Price', 0.0))})
    return jsonify({'price': 0.0}), 404

@api_bp.route('/charts/monthly-earnings')
@login_required
def get_monthly_earnings():
    """
    Groups payment logs by month (YYYY-MM) and returns sorted lists 
    for Chart.js rendering.
    """
    if _db.is_enabled():
        payments = _db.get_all_payments()
        date_key = 'payment_date'
        amount_key = 'amount_paid'
    else:
        payments = payment_model.get_all_payments()
        date_key = 'Payment Date'
        amount_key = 'Amount Paid'

    monthly_data = defaultdict(float)
    
    for p in payments:
        p_date = p.get(date_key, '')
        if p_date:
            try:
                # Extract YYYY-MM
                month = str(p_date)[:7]
                monthly_data[month] += float(p.get(amount_key, 0.0))
            except (ValueError, IndexError):
                pass
                
    # Sort months chronologically
    sorted_months = sorted(monthly_data.keys())
    values = [monthly_data[m] for m in sorted_months]
    
    # Format month labels (e.g., "2026-07" to "Jul 2026")
    formatted_labels = []
    for m in sorted_months:
        try:
            dt = datetime.strptime(m, '%Y-%m')
            formatted_labels.append(dt.strftime('%b %Y'))
        except ValueError:
            formatted_labels.append(m)
            
    return jsonify({
        'labels': formatted_labels,
        'values': values
    })

@api_bp.route('/charts/service-earnings')
@login_required
def get_service_earnings():
    """
    Calculates revenue share generated by each service category.
    """
    if _db.is_enabled():
        works = _db.get_all_work()
        service_key = 'service_name'
        total_key = 'total'
    else:
        works = work_model.get_all_work()
        service_key = 'Service Type'
        total_key = 'Total'

    service_revenue = defaultdict(float)
    
    for w in works:
        svc_name = w.get(service_key, 'Unknown') or 'Unknown'
        try:
            service_revenue[svc_name] += float(w.get(total_key, 0.0))
        except ValueError:
            pass
            
    # Sort by revenue descending
    sorted_services = sorted(service_revenue.items(), key=lambda x: x[1], reverse=True)
    
    labels = [item[0] for item in sorted_services]
    values = [item[1] for item in sorted_services]
    
    return jsonify({
        'labels': labels,
        'values': values
    })

@api_bp.route('/charts/payment-ratio')
@login_required
def get_payment_ratio():
    """
    Calculates the financial distribution of payments:
    - Paid: Cumulative money received.
    - Pending: Unpaid balances from 'Pending' work.
    - Partial Payment: Unpaid balances from 'Partial Payment' work.
    """
    if _db.is_enabled():
        works = _db.get_all_work()
        payments = _db.get_all_payments()
        
        paid_sum = sum(float(p.get('amount_paid', 0.0)) for p in payments)
        pending_sum = 0.0
        partial_sum = 0.0
        
        # Simulating work-level tracking for SQL DB by distributing client payments in FIFO order
        client_paid_rem = defaultdict(float)
        for p in payments:
            client_paid_rem[p.get('client_id')] += float(p.get('amount_paid', 0.0))
            
        sorted_works = sorted(works, key=lambda x: str(x.get('date', '')))
        for w in sorted_works:
            cid = w.get('client_id')
            w_total = float(w.get('total', 0.0))
            paid_for_this = min(w_total, client_paid_rem[cid])
            client_paid_rem[cid] -= paid_for_this
            w_outstanding = w_total - paid_for_this
            status = w.get('status', 'Pending')
            
            if w_outstanding > 0:
                if status == 'Pending':
                    pending_sum += w_outstanding
                elif status in ['Partial Payment', 'Partial']:
                    partial_sum += w_outstanding
    else:
        works = work_model.get_all_work()
        payments = payment_model.get_all_payments()
        
        paid_sum = sum(float(p.get('Amount Paid', 0.0)) for p in payments)
        pending_sum = 0.0
        partial_sum = 0.0
        
        for w in works:
            status = w.get('Status', 'Pending')
            try:
                w_total = float(w.get('Total', 0.0))
            except ValueError:
                w_total = 0.0
                
            w_paid = payment_model.get_total_paid_for_work(w.get('Serial Number'))
            w_outstanding = w_total - w_paid
            
            if w_outstanding > 0:
                if status == 'Pending':
                    pending_sum += w_outstanding
                elif status in ['Partial Payment', 'Partial']:
                    partial_sum += w_outstanding
                
    return jsonify({
        'paid': paid_sum,
        'pending': pending_sum,
        'partial': partial_sum
    })

@api_bp.route('/charts/client-revenue')
@login_required
def get_client_revenue():
    """
    Ranks the top 5 client accounts based on total billing revenue.
    """
    if _db.is_enabled():
        works = _db.get_all_work()
        name_key = 'client_name'
        total_key = 'total'
    else:
        works = work_model.get_all_work()
        name_key = 'Client Name'
        total_key = 'Total'

    client_revenue = defaultdict(float)
    
    for w in works:
        client_name = w.get(name_key, 'Unknown') or 'Unknown'
        try:
            client_revenue[client_name] += float(w.get(total_key, 0.0))
        except ValueError:
            pass
            
    # Sort descending and take top 5
    sorted_clients = sorted(client_revenue.items(), key=lambda x: x[1], reverse=True)[:5]
    
    labels = [item[0] for item in sorted_clients]
    values = [item[1] for item in sorted_clients]
    
    return jsonify({
        'labels': labels,
        'values': values
    })
